import type { NewDriveItem } from "@dg/drive/types";

export type { NewDriveItem, NewDriveShareItem } from "@dg/drive/types";

export const newDriveItems: NewDriveItem[] = [
  {
    id: "brand-assets",
    name: "Brand assets",
    kind: "folder",
    owner: "You",
    updated: "Today, 10:24 AM",
    size: "-",
    access: "Editors",
    spaceId: "darcygraphix-workspace",
    parentId: null,
  },
  {
    id: "production-files",
    name: "Production files",
    kind: "folder",
    owner: "You",
    updated: "Today, 9:41 AM",
    size: "-",
    access: "Editors",
    spaceId: "darcygraphix-workspace",
    parentId: null,
  },
  {
    id: "storefront-mockup",
    name: "Storefront mockup.png",
    kind: "image",
    owner: "You",
    updated: "Aug 5, 2026",
    size: "12.6 MB",
    access: "Restricted",
    spaceId: "darcygraphix-workspace",
    parentId: "brand-assets",
  },
  {
    id: "logo-package",
    name: "Logo package.pdf",
    kind: "pdf",
    owner: "Mara S.",
    updated: "Aug 4, 2026",
    size: "8.2 MB",
    access: "Editors",
    spaceId: "darcygraphix-workspace",
    parentId: "brand-assets",
  },
  {
    id: "client-proofs",
    name: "Client proofs",
    kind: "folder",
    owner: "You",
    updated: "Yesterday, 4:18 PM",
    size: "-",
    access: "Restricted",
    spaceId: "client-projects",
    parentId: null,
  },
  {
    id: "q3-campaign-brief",
    name: "Q3 campaign brief.pdf",
    kind: "pdf",
    owner: "Mara S.",
    updated: "Aug 6, 2026",
    size: "4.8 MB",
    access: "Viewers",
    spaceId: "client-projects",
    parentId: null,
  },
  {
    id: "proof-round-three",
    name: "Proof round 3.pdf",
    kind: "pdf",
    owner: "Ari D.",
    updated: "Today, 8:16 AM",
    size: "6.1 MB",
    access: "Viewers",
    spaceId: "client-projects",
    parentId: "client-proofs",
  },
  {
    id: "templates",
    name: "Templates",
    kind: "folder",
    owner: "You",
    updated: "Aug 5, 2026",
    size: "-",
    access: "Editors",
    spaceId: "team-resources",
    parentId: null,
  },
  {
    id: "print-specifications",
    name: "Print specifications.txt",
    kind: "text",
    owner: "Ari D.",
    updated: "Aug 2, 2026",
    size: "18 KB",
    access: "Viewers",
    spaceId: "team-resources",
    parentId: null,
  },
];
