/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteRouteImport } from './routes/_shop/route'
import { Route as ShopIndexRouteImport } from './routes/_shop/index'
import { Route as ShopOrderRouteImport } from './routes/_shop/order'
import { Route as ShopShowcaseIndexRouteImport } from './routes/_shop/showcase.index'
import { Route as ShareTokenChar123ItemIdChar125RouteImport } from './routes/share.$token.{-$itemId}'
import { Route as ShopShowcaseServiceRouteImport } from './routes/_shop/showcase.$service'

const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopOrderRoute = ShopOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopShowcaseIndexRoute = ShopShowcaseIndexRouteImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShareTokenChar123ItemIdChar125Route =
  ShareTokenChar123ItemIdChar125RouteImport.update({
    id: '/share/$token/{-$itemId}',
    path: '/share/$token/{-$itemId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopShowcaseServiceRoute = ShopShowcaseServiceRouteImport.update({
  id: '/showcase/$service',
  path: '/showcase/$service',
  getParentRoute: () => ShopRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/order': typeof ShopOrderRoute
  '/showcase/$service': typeof ShopShowcaseServiceRoute
  '/share/$token/{-$itemId}': typeof ShareTokenChar123ItemIdChar125Route
  '/showcase/': typeof ShopShowcaseIndexRoute
}
export interface FileRoutesByTo {
  '/order': typeof ShopOrderRoute
  '/': typeof ShopIndexRoute
  '/showcase/$service': typeof ShopShowcaseServiceRoute
  '/share/$token/{-$itemId}': typeof ShareTokenChar123ItemIdChar125Route
  '/showcase': typeof ShopShowcaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteRouteWithChildren
  '/_shop/order': typeof ShopOrderRoute
  '/_shop/': typeof ShopIndexRoute
  '/_shop/showcase/$service': typeof ShopShowcaseServiceRoute
  '/share/$token/{-$itemId}': typeof ShareTokenChar123ItemIdChar125Route
  '/_shop/showcase/': typeof ShopShowcaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order'
    | '/showcase/$service'
    | '/share/$token/{-$itemId}'
    | '/showcase/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/order'
    | '/'
    | '/showcase/$service'
    | '/share/$token/{-$itemId}'
    | '/showcase'
  id:
    | '__root__'
    | '/_shop'
    | '/_shop/order'
    | '/_shop/'
    | '/_shop/showcase/$service'
    | '/share/$token/{-$itemId}'
    | '/_shop/showcase/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRouteRoute: typeof ShopRouteRouteWithChildren
  ShareTokenChar123ItemIdChar125Route: typeof ShareTokenChar123ItemIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_shop/order': {
      id: '/_shop/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof ShopOrderRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_shop/showcase/': {
      id: '/_shop/showcase/'
      path: '/showcase'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShopShowcaseIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/share/$token/{-$itemId}': {
      id: '/share/$token/{-$itemId}'
      path: '/share/$token/{-$itemId}'
      fullPath: '/share/$token/{-$itemId}'
      preLoaderRoute: typeof ShareTokenChar123ItemIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/showcase/$service': {
      id: '/_shop/showcase/$service'
      path: '/showcase/$service'
      fullPath: '/showcase/$service'
      preLoaderRoute: typeof ShopShowcaseServiceRouteImport
      parentRoute: typeof ShopRouteRoute
    }
  }
}

interface ShopRouteRouteChildren {
  ShopOrderRoute: typeof ShopOrderRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopShowcaseServiceRoute: typeof ShopShowcaseServiceRoute
  ShopShowcaseIndexRoute: typeof ShopShowcaseIndexRoute
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopOrderRoute: ShopOrderRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopShowcaseServiceRoute: ShopShowcaseServiceRoute,
  ShopShowcaseIndexRoute: ShopShowcaseIndexRoute,
}

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShopRouteRoute: ShopRouteRouteWithChildren,
  ShareTokenChar123ItemIdChar125Route: ShareTokenChar123ItemIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
