/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenChar123ItemIdChar125RouteImport } from './routes/share.$token.{-$itemId}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenChar123ItemIdChar125Route =
  ShareTokenChar123ItemIdChar125RouteImport.update({
    id: '/share/$token/{-$itemId}',
    path: '/share/$token/{-$itemId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share/$token/{-$itemId}': typeof ShareTokenChar123ItemIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share/$token/{-$itemId}': typeof ShareTokenChar123ItemIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/share/$token/{-$itemId}': typeof ShareTokenChar123ItemIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/share/$token/{-$itemId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/share/$token/{-$itemId}'
  id: '__root__' | '/' | '/share/$token/{-$itemId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareTokenChar123ItemIdChar125Route: typeof ShareTokenChar123ItemIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token/{-$itemId}': {
      id: '/share/$token/{-$itemId}'
      path: '/share/$token/{-$itemId}'
      fullPath: '/share/$token/{-$itemId}'
      preLoaderRoute: typeof ShareTokenChar123ItemIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareTokenChar123ItemIdChar125Route: ShareTokenChar123ItemIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
