/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as AuthenticatedNewdriveRouteImport } from './routes/_authenticated/newdrive'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedDriveRouteImport } from './routes/_authenticated/drive'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedCashierRouteRouteImport } from './routes/_authenticated/_cashier/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedTrelloIndexRouteImport } from './routes/_authenticated/trello.index'
import { Route as AuthenticatedNewdriveIndexRouteImport } from './routes/_authenticated/newdrive.index'
import { Route as AuthenticatedJoIndexRouteImport } from './routes/_authenticated/jo.index'
import { Route as AuthenticatedDriveIndexRouteImport } from './routes/_authenticated/drive.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthenticatedTrelloListIdRouteImport } from './routes/_authenticated/trello.$listId'
import { Route as AuthenticatedJoJoIdRouteImport } from './routes/_authenticated/jo.$joId'
import { Route as AuthenticatedInventoryIdRouteImport } from './routes/_authenticated/inventory_.$id'
import { Route as AuthenticatedCashierCashflowRouteImport } from './routes/_authenticated/_cashier/cashflow'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedNewdriveFileItemIdRouteImport } from './routes/_authenticated/newdrive.file.$itemId'
import { Route as AuthenticatedNewdriveSpaceIdChar123FolderIdChar125RouteImport } from './routes/_authenticated/newdrive.$spaceId.{-$folderId}'
import { Route as AuthenticatedDriveFileItemIdRouteImport } from './routes/_authenticated/drive.file.$itemId'
import { Route as AuthenticatedDriveSpaceIdChar123FolderIdChar125RouteImport } from './routes/_authenticated/drive.$spaceId.{-$folderId}'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminSuppliersRouteImport } from './routes/_authenticated/_admin/admin.suppliers'
import { Route as AuthenticatedAdminAdminCustomersRouteImport } from './routes/_authenticated/_admin/admin.customers'
import { Route as AuthenticatedAdminAdminSuppliersIndexRouteImport } from './routes/_authenticated/_admin/admin.suppliers.index'
import { Route as AuthenticatedAdminAdminCustomersIndexRouteImport } from './routes/_authenticated/_admin/admin.customers.index'
import { Route as AuthenticatedAdminAdminSuppliersSupplierIdRouteImport } from './routes/_authenticated/_admin/admin.suppliers.$supplierId'
import { Route as AuthenticatedAdminAdminCustomersCustomerIdRouteImport } from './routes/_authenticated/_admin/admin.customers.$customerId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/app/$',
  path: '/app/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewdriveRoute = AuthenticatedNewdriveRouteImport.update({
  id: '/newdrive',
  path: '/newdrive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriveRoute = AuthenticatedDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedCashierRouteRoute =
  AuthenticatedCashierRouteRouteImport.update({
    id: '/_cashier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrelloIndexRoute =
  AuthenticatedTrelloIndexRouteImport.update({
    id: '/trello/',
    path: '/trello/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewdriveIndexRoute =
  AuthenticatedNewdriveIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNewdriveRoute,
  } as any)
const AuthenticatedJoIndexRoute = AuthenticatedJoIndexRouteImport.update({
  id: '/jo/',
  path: '/jo/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriveIndexRoute = AuthenticatedDriveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDriveRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrelloListIdRoute =
  AuthenticatedTrelloListIdRouteImport.update({
    id: '/trello/$listId',
    path: '/trello/$listId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJoJoIdRoute = AuthenticatedJoJoIdRouteImport.update({
  id: '/jo/$joId',
  path: '/jo/$joId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryIdRoute =
  AuthenticatedInventoryIdRouteImport.update({
    id: '/inventory_/$id',
    path: '/inventory/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashierCashflowRoute =
  AuthenticatedCashierCashflowRouteImport.update({
    id: '/cashflow',
    path: '/cashflow',
    getParentRoute: () => AuthenticatedCashierRouteRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedNewdriveFileItemIdRoute =
  AuthenticatedNewdriveFileItemIdRouteImport.update({
    id: '/file/$itemId',
    path: '/file/$itemId',
    getParentRoute: () => AuthenticatedNewdriveRoute,
  } as any)
const AuthenticatedNewdriveSpaceIdChar123FolderIdChar125Route =
  AuthenticatedNewdriveSpaceIdChar123FolderIdChar125RouteImport.update({
    id: '/$spaceId/{-$folderId}',
    path: '/$spaceId/{-$folderId}',
    getParentRoute: () => AuthenticatedNewdriveRoute,
  } as any)
const AuthenticatedDriveFileItemIdRoute =
  AuthenticatedDriveFileItemIdRouteImport.update({
    id: '/file/$itemId',
    path: '/file/$itemId',
    getParentRoute: () => AuthenticatedDriveRoute,
  } as any)
const AuthenticatedDriveSpaceIdChar123FolderIdChar125Route =
  AuthenticatedDriveSpaceIdChar123FolderIdChar125RouteImport.update({
    id: '/$spaceId/{-$folderId}',
    path: '/$spaceId/{-$folderId}',
    getParentRoute: () => AuthenticatedDriveRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminSuppliersRoute =
  AuthenticatedAdminAdminSuppliersRouteImport.update({
    id: '/admin/suppliers',
    path: '/admin/suppliers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminCustomersRoute =
  AuthenticatedAdminAdminCustomersRouteImport.update({
    id: '/admin/customers',
    path: '/admin/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminSuppliersIndexRoute =
  AuthenticatedAdminAdminSuppliersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminSuppliersRoute,
  } as any)
const AuthenticatedAdminAdminCustomersIndexRoute =
  AuthenticatedAdminAdminCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminCustomersRoute,
  } as any)
const AuthenticatedAdminAdminSuppliersSupplierIdRoute =
  AuthenticatedAdminAdminSuppliersSupplierIdRouteImport.update({
    id: '/$supplierId',
    path: '/$supplierId',
    getParentRoute: () => AuthenticatedAdminAdminSuppliersRoute,
  } as any)
const AuthenticatedAdminAdminCustomersCustomerIdRoute =
  AuthenticatedAdminAdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedAdminAdminCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/drive': typeof AuthenticatedDriveRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/newdrive': typeof AuthenticatedNewdriveRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/app/': typeof AppIndexRoute
  '/cashflow': typeof AuthenticatedCashierCashflowRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/jo/$joId': typeof AuthenticatedJoJoIdRoute
  '/trello/$listId': typeof AuthenticatedTrelloListIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/drive/': typeof AuthenticatedDriveIndexRoute
  '/jo/': typeof AuthenticatedJoIndexRoute
  '/newdrive/': typeof AuthenticatedNewdriveIndexRoute
  '/trello/': typeof AuthenticatedTrelloIndexRoute
  '/admin/customers': typeof AuthenticatedAdminAdminCustomersRouteWithChildren
  '/admin/suppliers': typeof AuthenticatedAdminAdminSuppliersRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/drive/$spaceId/{-$folderId}': typeof AuthenticatedDriveSpaceIdChar123FolderIdChar125Route
  '/drive/file/$itemId': typeof AuthenticatedDriveFileItemIdRoute
  '/newdrive/$spaceId/{-$folderId}': typeof AuthenticatedNewdriveSpaceIdChar123FolderIdChar125Route
  '/newdrive/file/$itemId': typeof AuthenticatedNewdriveFileItemIdRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/customers/$customerId': typeof AuthenticatedAdminAdminCustomersCustomerIdRoute
  '/admin/suppliers/$supplierId': typeof AuthenticatedAdminAdminSuppliersSupplierIdRoute
  '/admin/customers/': typeof AuthenticatedAdminAdminCustomersIndexRoute
  '/admin/suppliers/': typeof AuthenticatedAdminAdminSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/app/$': typeof AppSplatRoute
  '/app': typeof AppIndexRoute
  '/cashflow': typeof AuthenticatedCashierCashflowRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/jo/$joId': typeof AuthenticatedJoJoIdRoute
  '/trello/$listId': typeof AuthenticatedTrelloListIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/drive': typeof AuthenticatedDriveIndexRoute
  '/jo': typeof AuthenticatedJoIndexRoute
  '/newdrive': typeof AuthenticatedNewdriveIndexRoute
  '/trello': typeof AuthenticatedTrelloIndexRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/drive/$spaceId/{-$folderId}': typeof AuthenticatedDriveSpaceIdChar123FolderIdChar125Route
  '/drive/file/$itemId': typeof AuthenticatedDriveFileItemIdRoute
  '/newdrive/$spaceId/{-$folderId}': typeof AuthenticatedNewdriveSpaceIdChar123FolderIdChar125Route
  '/newdrive/file/$itemId': typeof AuthenticatedNewdriveFileItemIdRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/customers/$customerId': typeof AuthenticatedAdminAdminCustomersCustomerIdRoute
  '/admin/suppliers/$supplierId': typeof AuthenticatedAdminAdminSuppliersSupplierIdRoute
  '/admin/customers': typeof AuthenticatedAdminAdminCustomersIndexRoute
  '/admin/suppliers': typeof AuthenticatedAdminAdminSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/_cashier': typeof AuthenticatedCashierRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/drive': typeof AuthenticatedDriveRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/newdrive': typeof AuthenticatedNewdriveRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/app/': typeof AppIndexRoute
  '/_authenticated/_cashier/cashflow': typeof AuthenticatedCashierCashflowRoute
  '/_authenticated/inventory_/$id': typeof AuthenticatedInventoryIdRoute
  '/_authenticated/jo/$joId': typeof AuthenticatedJoJoIdRoute
  '/_authenticated/trello/$listId': typeof AuthenticatedTrelloListIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/drive/': typeof AuthenticatedDriveIndexRoute
  '/_authenticated/jo/': typeof AuthenticatedJoIndexRoute
  '/_authenticated/newdrive/': typeof AuthenticatedNewdriveIndexRoute
  '/_authenticated/trello/': typeof AuthenticatedTrelloIndexRoute
  '/_authenticated/_admin/admin/customers': typeof AuthenticatedAdminAdminCustomersRouteWithChildren
  '/_authenticated/_admin/admin/suppliers': typeof AuthenticatedAdminAdminSuppliersRouteWithChildren
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/drive/$spaceId/{-$folderId}': typeof AuthenticatedDriveSpaceIdChar123FolderIdChar125Route
  '/_authenticated/drive/file/$itemId': typeof AuthenticatedDriveFileItemIdRoute
  '/_authenticated/newdrive/$spaceId/{-$folderId}': typeof AuthenticatedNewdriveSpaceIdChar123FolderIdChar125Route
  '/_authenticated/newdrive/file/$itemId': typeof AuthenticatedNewdriveFileItemIdRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/customers/$customerId': typeof AuthenticatedAdminAdminCustomersCustomerIdRoute
  '/_authenticated/_admin/admin/suppliers/$supplierId': typeof AuthenticatedAdminAdminSuppliersSupplierIdRoute
  '/_authenticated/_admin/admin/customers/': typeof AuthenticatedAdminAdminCustomersIndexRoute
  '/_authenticated/_admin/admin/suppliers/': typeof AuthenticatedAdminAdminSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/drive'
    | '/inventory'
    | '/newdrive'
    | '/app/$'
    | '/app/'
    | '/cashflow'
    | '/inventory/$id'
    | '/jo/$joId'
    | '/trello/$listId'
    | '/api/auth/$'
    | '/drive/'
    | '/jo/'
    | '/newdrive/'
    | '/trello/'
    | '/admin/customers'
    | '/admin/suppliers'
    | '/admin/users'
    | '/drive/$spaceId/{-$folderId}'
    | '/drive/file/$itemId'
    | '/newdrive/$spaceId/{-$folderId}'
    | '/newdrive/file/$itemId'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/admin/suppliers/$supplierId'
    | '/admin/customers/'
    | '/admin/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/inventory'
    | '/app/$'
    | '/app'
    | '/cashflow'
    | '/inventory/$id'
    | '/jo/$joId'
    | '/trello/$listId'
    | '/api/auth/$'
    | '/drive'
    | '/jo'
    | '/newdrive'
    | '/trello'
    | '/admin/users'
    | '/drive/$spaceId/{-$folderId}'
    | '/drive/file/$itemId'
    | '/newdrive/$spaceId/{-$folderId}'
    | '/newdrive/file/$itemId'
    | '/admin'
    | '/admin/customers/$customerId'
    | '/admin/suppliers/$supplierId'
    | '/admin/customers'
    | '/admin/suppliers'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/_admin'
    | '/_authenticated/_cashier'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authenticated/drive'
    | '/_authenticated/inventory'
    | '/_authenticated/newdrive'
    | '/app/$'
    | '/_authenticated/'
    | '/app/'
    | '/_authenticated/_cashier/cashflow'
    | '/_authenticated/inventory_/$id'
    | '/_authenticated/jo/$joId'
    | '/_authenticated/trello/$listId'
    | '/api/auth/$'
    | '/_authenticated/drive/'
    | '/_authenticated/jo/'
    | '/_authenticated/newdrive/'
    | '/_authenticated/trello/'
    | '/_authenticated/_admin/admin/customers'
    | '/_authenticated/_admin/admin/suppliers'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/drive/$spaceId/{-$folderId}'
    | '/_authenticated/drive/file/$itemId'
    | '/_authenticated/newdrive/$spaceId/{-$folderId}'
    | '/_authenticated/newdrive/file/$itemId'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/customers/$customerId'
    | '/_authenticated/_admin/admin/suppliers/$supplierId'
    | '/_authenticated/_admin/admin/customers/'
    | '/_authenticated/_admin/admin/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppSplatRoute: typeof AppSplatRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/app/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/newdrive': {
      id: '/_authenticated/newdrive'
      path: '/newdrive'
      fullPath: '/newdrive'
      preLoaderRoute: typeof AuthenticatedNewdriveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive': {
      id: '/_authenticated/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof AuthenticatedDriveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/_cashier': {
      id: '/_authenticated/_cashier'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedCashierRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trello/': {
      id: '/_authenticated/trello/'
      path: '/trello'
      fullPath: '/trello/'
      preLoaderRoute: typeof AuthenticatedTrelloIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/newdrive/': {
      id: '/_authenticated/newdrive/'
      path: '/'
      fullPath: '/newdrive/'
      preLoaderRoute: typeof AuthenticatedNewdriveIndexRouteImport
      parentRoute: typeof AuthenticatedNewdriveRoute
    }
    '/_authenticated/jo/': {
      id: '/_authenticated/jo/'
      path: '/jo'
      fullPath: '/jo/'
      preLoaderRoute: typeof AuthenticatedJoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/': {
      id: '/_authenticated/drive/'
      path: '/'
      fullPath: '/drive/'
      preLoaderRoute: typeof AuthenticatedDriveIndexRouteImport
      parentRoute: typeof AuthenticatedDriveRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trello/$listId': {
      id: '/_authenticated/trello/$listId'
      path: '/trello/$listId'
      fullPath: '/trello/$listId'
      preLoaderRoute: typeof AuthenticatedTrelloListIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jo/$joId': {
      id: '/_authenticated/jo/$joId'
      path: '/jo/$joId'
      fullPath: '/jo/$joId'
      preLoaderRoute: typeof AuthenticatedJoJoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory_/$id': {
      id: '/_authenticated/inventory_/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AuthenticatedInventoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_cashier/cashflow': {
      id: '/_authenticated/_cashier/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof AuthenticatedCashierCashflowRouteImport
      parentRoute: typeof AuthenticatedCashierRouteRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/newdrive/file/$itemId': {
      id: '/_authenticated/newdrive/file/$itemId'
      path: '/file/$itemId'
      fullPath: '/newdrive/file/$itemId'
      preLoaderRoute: typeof AuthenticatedNewdriveFileItemIdRouteImport
      parentRoute: typeof AuthenticatedNewdriveRoute
    }
    '/_authenticated/newdrive/$spaceId/{-$folderId}': {
      id: '/_authenticated/newdrive/$spaceId/{-$folderId}'
      path: '/$spaceId/{-$folderId}'
      fullPath: '/newdrive/$spaceId/{-$folderId}'
      preLoaderRoute: typeof AuthenticatedNewdriveSpaceIdChar123FolderIdChar125RouteImport
      parentRoute: typeof AuthenticatedNewdriveRoute
    }
    '/_authenticated/drive/file/$itemId': {
      id: '/_authenticated/drive/file/$itemId'
      path: '/file/$itemId'
      fullPath: '/drive/file/$itemId'
      preLoaderRoute: typeof AuthenticatedDriveFileItemIdRouteImport
      parentRoute: typeof AuthenticatedDriveRoute
    }
    '/_authenticated/drive/$spaceId/{-$folderId}': {
      id: '/_authenticated/drive/$spaceId/{-$folderId}'
      path: '/$spaceId/{-$folderId}'
      fullPath: '/drive/$spaceId/{-$folderId}'
      preLoaderRoute: typeof AuthenticatedDriveSpaceIdChar123FolderIdChar125RouteImport
      parentRoute: typeof AuthenticatedDriveRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/suppliers': {
      id: '/_authenticated/_admin/admin/suppliers'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminAdminSuppliersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/customers': {
      id: '/_authenticated/_admin/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/suppliers/': {
      id: '/_authenticated/_admin/admin/suppliers/'
      path: '/'
      fullPath: '/admin/suppliers/'
      preLoaderRoute: typeof AuthenticatedAdminAdminSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminSuppliersRoute
    }
    '/_authenticated/_admin/admin/customers/': {
      id: '/_authenticated/_admin/admin/customers/'
      path: '/'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AuthenticatedAdminAdminCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminCustomersRoute
    }
    '/_authenticated/_admin/admin/suppliers/$supplierId': {
      id: '/_authenticated/_admin/admin/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/admin/suppliers/$supplierId'
      preLoaderRoute: typeof AuthenticatedAdminAdminSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthenticatedAdminAdminSuppliersRoute
    }
    '/_authenticated/_admin/admin/customers/$customerId': {
      id: '/_authenticated/_admin/admin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedAdminAdminCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedAdminAdminCustomersRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedAdminAdminCustomersRouteChildren {
  AuthenticatedAdminAdminCustomersCustomerIdRoute: typeof AuthenticatedAdminAdminCustomersCustomerIdRoute
  AuthenticatedAdminAdminCustomersIndexRoute: typeof AuthenticatedAdminAdminCustomersIndexRoute
}

const AuthenticatedAdminAdminCustomersRouteChildren: AuthenticatedAdminAdminCustomersRouteChildren =
  {
    AuthenticatedAdminAdminCustomersCustomerIdRoute:
      AuthenticatedAdminAdminCustomersCustomerIdRoute,
    AuthenticatedAdminAdminCustomersIndexRoute:
      AuthenticatedAdminAdminCustomersIndexRoute,
  }

const AuthenticatedAdminAdminCustomersRouteWithChildren =
  AuthenticatedAdminAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminAdminSuppliersRouteChildren {
  AuthenticatedAdminAdminSuppliersSupplierIdRoute: typeof AuthenticatedAdminAdminSuppliersSupplierIdRoute
  AuthenticatedAdminAdminSuppliersIndexRoute: typeof AuthenticatedAdminAdminSuppliersIndexRoute
}

const AuthenticatedAdminAdminSuppliersRouteChildren: AuthenticatedAdminAdminSuppliersRouteChildren =
  {
    AuthenticatedAdminAdminSuppliersSupplierIdRoute:
      AuthenticatedAdminAdminSuppliersSupplierIdRoute,
    AuthenticatedAdminAdminSuppliersIndexRoute:
      AuthenticatedAdminAdminSuppliersIndexRoute,
  }

const AuthenticatedAdminAdminSuppliersRouteWithChildren =
  AuthenticatedAdminAdminSuppliersRoute._addFileChildren(
    AuthenticatedAdminAdminSuppliersRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminCustomersRoute: typeof AuthenticatedAdminAdminCustomersRouteWithChildren
  AuthenticatedAdminAdminSuppliersRoute: typeof AuthenticatedAdminAdminSuppliersRouteWithChildren
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminCustomersRoute:
      AuthenticatedAdminAdminCustomersRouteWithChildren,
    AuthenticatedAdminAdminSuppliersRoute:
      AuthenticatedAdminAdminSuppliersRouteWithChildren,
    AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCashierRouteRouteChildren {
  AuthenticatedCashierCashflowRoute: typeof AuthenticatedCashierCashflowRoute
}

const AuthenticatedCashierRouteRouteChildren: AuthenticatedCashierRouteRouteChildren =
  {
    AuthenticatedCashierCashflowRoute: AuthenticatedCashierCashflowRoute,
  }

const AuthenticatedCashierRouteRouteWithChildren =
  AuthenticatedCashierRouteRoute._addFileChildren(
    AuthenticatedCashierRouteRouteChildren,
  )

interface AuthenticatedDriveRouteChildren {
  AuthenticatedDriveIndexRoute: typeof AuthenticatedDriveIndexRoute
  AuthenticatedDriveSpaceIdChar123FolderIdChar125Route: typeof AuthenticatedDriveSpaceIdChar123FolderIdChar125Route
  AuthenticatedDriveFileItemIdRoute: typeof AuthenticatedDriveFileItemIdRoute
}

const AuthenticatedDriveRouteChildren: AuthenticatedDriveRouteChildren = {
  AuthenticatedDriveIndexRoute: AuthenticatedDriveIndexRoute,
  AuthenticatedDriveSpaceIdChar123FolderIdChar125Route:
    AuthenticatedDriveSpaceIdChar123FolderIdChar125Route,
  AuthenticatedDriveFileItemIdRoute: AuthenticatedDriveFileItemIdRoute,
}

const AuthenticatedDriveRouteWithChildren =
  AuthenticatedDriveRoute._addFileChildren(AuthenticatedDriveRouteChildren)

interface AuthenticatedNewdriveRouteChildren {
  AuthenticatedNewdriveIndexRoute: typeof AuthenticatedNewdriveIndexRoute
  AuthenticatedNewdriveSpaceIdChar123FolderIdChar125Route: typeof AuthenticatedNewdriveSpaceIdChar123FolderIdChar125Route
  AuthenticatedNewdriveFileItemIdRoute: typeof AuthenticatedNewdriveFileItemIdRoute
}

const AuthenticatedNewdriveRouteChildren: AuthenticatedNewdriveRouteChildren = {
  AuthenticatedNewdriveIndexRoute: AuthenticatedNewdriveIndexRoute,
  AuthenticatedNewdriveSpaceIdChar123FolderIdChar125Route:
    AuthenticatedNewdriveSpaceIdChar123FolderIdChar125Route,
  AuthenticatedNewdriveFileItemIdRoute: AuthenticatedNewdriveFileItemIdRoute,
}

const AuthenticatedNewdriveRouteWithChildren =
  AuthenticatedNewdriveRoute._addFileChildren(
    AuthenticatedNewdriveRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCashierRouteRoute: typeof AuthenticatedCashierRouteRouteWithChildren
  AuthenticatedDriveRoute: typeof AuthenticatedDriveRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedNewdriveRoute: typeof AuthenticatedNewdriveRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInventoryIdRoute: typeof AuthenticatedInventoryIdRoute
  AuthenticatedJoJoIdRoute: typeof AuthenticatedJoJoIdRoute
  AuthenticatedTrelloListIdRoute: typeof AuthenticatedTrelloListIdRoute
  AuthenticatedJoIndexRoute: typeof AuthenticatedJoIndexRoute
  AuthenticatedTrelloIndexRoute: typeof AuthenticatedTrelloIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCashierRouteRoute: AuthenticatedCashierRouteRouteWithChildren,
  AuthenticatedDriveRoute: AuthenticatedDriveRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedNewdriveRoute: AuthenticatedNewdriveRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInventoryIdRoute: AuthenticatedInventoryIdRoute,
  AuthenticatedJoJoIdRoute: AuthenticatedJoJoIdRoute,
  AuthenticatedTrelloListIdRoute: AuthenticatedTrelloListIdRoute,
  AuthenticatedJoIndexRoute: AuthenticatedJoIndexRoute,
  AuthenticatedTrelloIndexRoute: AuthenticatedTrelloIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppSplatRoute: AppSplatRoute,
  AppIndexRoute: AppIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
