/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestfruitsRouteImport } from './routes/testfruits'
import { Route as TestdndRouteImport } from './routes/testdnd'
import { Route as ConvexRouteImport } from './routes/convex'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainThreeRouteImport } from './routes/_main/three'
import { Route as MainTesttrelloRouteImport } from './routes/_main/testtrello'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as MainCashierRouteRouteImport } from './routes/_main/_cashier/route'
import { Route as MainAdminRouteRouteImport } from './routes/_main/_admin/route'
import { Route as MainTrelloIndexRouteImport } from './routes/_main/trello.index'
import { Route as MainJoIndexRouteImport } from './routes/_main/jo.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as MainTrelloListIdRouteImport } from './routes/_main/trello.$listId'
import { Route as MainJoJoIdRouteImport } from './routes/_main/jo.$joId'
import { Route as MainDriveChar123DriveChar125RouteImport } from './routes/_main/drive.{-$drive}'
import { Route as MainCashierCashflowRouteImport } from './routes/_main/_cashier/cashflow'
import { Route as MainAdminAdminIndexRouteImport } from './routes/_main/_admin/admin.index'
import { Route as MainAdminAdminUsersRouteImport } from './routes/_main/_admin/admin.users'

const TestfruitsRoute = TestfruitsRouteImport.update({
  id: '/testfruits',
  path: '/testfruits',
  getParentRoute: () => rootRouteImport,
} as any)
const TestdndRoute = TestdndRouteImport.update({
  id: '/testdnd',
  path: '/testdnd',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvexRoute = ConvexRouteImport.update({
  id: '/convex',
  path: '/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainThreeRoute = MainThreeRouteImport.update({
  id: '/three',
  path: '/three',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTesttrelloRoute = MainTesttrelloRouteImport.update({
  id: '/testtrello',
  path: '/testtrello',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainCashierRouteRoute = MainCashierRouteRouteImport.update({
  id: '/_cashier',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminRouteRoute = MainAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTrelloIndexRoute = MainTrelloIndexRouteImport.update({
  id: '/trello/',
  path: '/trello/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainJoIndexRoute = MainJoIndexRouteImport.update({
  id: '/jo/',
  path: '/jo/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainTrelloListIdRoute = MainTrelloListIdRouteImport.update({
  id: '/trello/$listId',
  path: '/trello/$listId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainJoJoIdRoute = MainJoJoIdRouteImport.update({
  id: '/jo/$joId',
  path: '/jo/$joId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDriveChar123DriveChar125Route =
  MainDriveChar123DriveChar125RouteImport.update({
    id: '/drive/{-$drive}',
    path: '/drive/{-$drive}',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainCashierCashflowRoute = MainCashierCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => MainCashierRouteRoute,
} as any)
const MainAdminAdminIndexRoute = MainAdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => MainAdminRouteRoute,
} as any)
const MainAdminAdminUsersRoute = MainAdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => MainAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convex': typeof ConvexRoute
  '/testdnd': typeof TestdndRoute
  '/testfruits': typeof TestfruitsRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/testtrello': typeof MainTesttrelloRoute
  '/three': typeof MainThreeRoute
  '/cashflow': typeof MainCashierCashflowRoute
  '/drive/{-$drive}': typeof MainDriveChar123DriveChar125Route
  '/jo/$joId': typeof MainJoJoIdRoute
  '/trello/$listId': typeof MainTrelloListIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/jo/': typeof MainJoIndexRoute
  '/trello/': typeof MainTrelloIndexRoute
  '/admin/users': typeof MainAdminAdminUsersRoute
  '/admin/': typeof MainAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convex': typeof ConvexRoute
  '/testdnd': typeof TestdndRoute
  '/testfruits': typeof TestfruitsRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/testtrello': typeof MainTesttrelloRoute
  '/three': typeof MainThreeRoute
  '/cashflow': typeof MainCashierCashflowRoute
  '/drive/{-$drive}': typeof MainDriveChar123DriveChar125Route
  '/jo/$joId': typeof MainJoJoIdRoute
  '/trello/$listId': typeof MainTrelloListIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/jo': typeof MainJoIndexRoute
  '/trello': typeof MainTrelloIndexRoute
  '/admin/users': typeof MainAdminAdminUsersRoute
  '/admin': typeof MainAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/convex': typeof ConvexRoute
  '/testdnd': typeof TestdndRoute
  '/testfruits': typeof TestfruitsRoute
  '/_main/_admin': typeof MainAdminRouteRouteWithChildren
  '/_main/_cashier': typeof MainCashierRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_main/testtrello': typeof MainTesttrelloRoute
  '/_main/three': typeof MainThreeRoute
  '/_main/_cashier/cashflow': typeof MainCashierCashflowRoute
  '/_main/drive/{-$drive}': typeof MainDriveChar123DriveChar125Route
  '/_main/jo/$joId': typeof MainJoJoIdRoute
  '/_main/trello/$listId': typeof MainTrelloListIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_main/jo/': typeof MainJoIndexRoute
  '/_main/trello/': typeof MainTrelloIndexRoute
  '/_main/_admin/admin/users': typeof MainAdminAdminUsersRoute
  '/_main/_admin/admin/': typeof MainAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convex'
    | '/testdnd'
    | '/testfruits'
    | '/login'
    | '/signup'
    | '/testtrello'
    | '/three'
    | '/cashflow'
    | '/drive/{-$drive}'
    | '/jo/$joId'
    | '/trello/$listId'
    | '/api/auth/$'
    | '/jo/'
    | '/trello/'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convex'
    | '/testdnd'
    | '/testfruits'
    | '/login'
    | '/signup'
    | '/testtrello'
    | '/three'
    | '/cashflow'
    | '/drive/{-$drive}'
    | '/jo/$joId'
    | '/trello/$listId'
    | '/api/auth/$'
    | '/jo'
    | '/trello'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/convex'
    | '/testdnd'
    | '/testfruits'
    | '/_main/_admin'
    | '/_main/_cashier'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_main/testtrello'
    | '/_main/three'
    | '/_main/_cashier/cashflow'
    | '/_main/drive/{-$drive}'
    | '/_main/jo/$joId'
    | '/_main/trello/$listId'
    | '/api/auth/$'
    | '/_main/jo/'
    | '/_main/trello/'
    | '/_main/_admin/admin/users'
    | '/_main/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ConvexRoute: typeof ConvexRoute
  TestdndRoute: typeof TestdndRoute
  TestfruitsRoute: typeof TestfruitsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testfruits': {
      id: '/testfruits'
      path: '/testfruits'
      fullPath: '/testfruits'
      preLoaderRoute: typeof TestfruitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testdnd': {
      id: '/testdnd'
      path: '/testdnd'
      fullPath: '/testdnd'
      preLoaderRoute: typeof TestdndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convex': {
      id: '/convex'
      path: '/convex'
      fullPath: '/convex'
      preLoaderRoute: typeof ConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/three': {
      id: '/_main/three'
      path: '/three'
      fullPath: '/three'
      preLoaderRoute: typeof MainThreeRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/testtrello': {
      id: '/_main/testtrello'
      path: '/testtrello'
      fullPath: '/testtrello'
      preLoaderRoute: typeof MainTesttrelloRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/_cashier': {
      id: '/_main/_cashier'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainCashierRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_admin': {
      id: '/_main/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainAdminRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/trello/': {
      id: '/_main/trello/'
      path: '/trello'
      fullPath: '/trello/'
      preLoaderRoute: typeof MainTrelloIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/jo/': {
      id: '/_main/jo/'
      path: '/jo'
      fullPath: '/jo/'
      preLoaderRoute: typeof MainJoIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/trello/$listId': {
      id: '/_main/trello/$listId'
      path: '/trello/$listId'
      fullPath: '/trello/$listId'
      preLoaderRoute: typeof MainTrelloListIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/jo/$joId': {
      id: '/_main/jo/$joId'
      path: '/jo/$joId'
      fullPath: '/jo/$joId'
      preLoaderRoute: typeof MainJoJoIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/drive/{-$drive}': {
      id: '/_main/drive/{-$drive}'
      path: '/drive/{-$drive}'
      fullPath: '/drive/{-$drive}'
      preLoaderRoute: typeof MainDriveChar123DriveChar125RouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_cashier/cashflow': {
      id: '/_main/_cashier/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof MainCashierCashflowRouteImport
      parentRoute: typeof MainCashierRouteRoute
    }
    '/_main/_admin/admin/': {
      id: '/_main/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof MainAdminAdminIndexRouteImport
      parentRoute: typeof MainAdminRouteRoute
    }
    '/_main/_admin/admin/users': {
      id: '/_main/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof MainAdminAdminUsersRouteImport
      parentRoute: typeof MainAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainAdminRouteRouteChildren {
  MainAdminAdminUsersRoute: typeof MainAdminAdminUsersRoute
  MainAdminAdminIndexRoute: typeof MainAdminAdminIndexRoute
}

const MainAdminRouteRouteChildren: MainAdminRouteRouteChildren = {
  MainAdminAdminUsersRoute: MainAdminAdminUsersRoute,
  MainAdminAdminIndexRoute: MainAdminAdminIndexRoute,
}

const MainAdminRouteRouteWithChildren = MainAdminRouteRoute._addFileChildren(
  MainAdminRouteRouteChildren,
)

interface MainCashierRouteRouteChildren {
  MainCashierCashflowRoute: typeof MainCashierCashflowRoute
}

const MainCashierRouteRouteChildren: MainCashierRouteRouteChildren = {
  MainCashierCashflowRoute: MainCashierCashflowRoute,
}

const MainCashierRouteRouteWithChildren =
  MainCashierRouteRoute._addFileChildren(MainCashierRouteRouteChildren)

interface MainRouteRouteChildren {
  MainAdminRouteRoute: typeof MainAdminRouteRouteWithChildren
  MainCashierRouteRoute: typeof MainCashierRouteRouteWithChildren
  MainTesttrelloRoute: typeof MainTesttrelloRoute
  MainThreeRoute: typeof MainThreeRoute
  MainDriveChar123DriveChar125Route: typeof MainDriveChar123DriveChar125Route
  MainJoJoIdRoute: typeof MainJoJoIdRoute
  MainTrelloListIdRoute: typeof MainTrelloListIdRoute
  MainJoIndexRoute: typeof MainJoIndexRoute
  MainTrelloIndexRoute: typeof MainTrelloIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAdminRouteRoute: MainAdminRouteRouteWithChildren,
  MainCashierRouteRoute: MainCashierRouteRouteWithChildren,
  MainTesttrelloRoute: MainTesttrelloRoute,
  MainThreeRoute: MainThreeRoute,
  MainDriveChar123DriveChar125Route: MainDriveChar123DriveChar125Route,
  MainJoJoIdRoute: MainJoJoIdRoute,
  MainTrelloListIdRoute: MainTrelloListIdRoute,
  MainJoIndexRoute: MainJoIndexRoute,
  MainTrelloIndexRoute: MainTrelloIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  ConvexRoute: ConvexRoute,
  TestdndRoute: TestdndRoute,
  TestfruitsRoute: TestfruitsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
